name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo 'Hello World!'
      - name: Print Goodby
        run: echo 'Done- by!'
